export interface ScopeEntry {
  item: string
  rationale: string
}

export const IN_SCOPE: ScopeEntry[] = [
  {
    item: 'Org-level analytics dashboard',
    rationale:
      'The primary deliverable: a single dashboard surfacing all 38 KPIs and charts for one organization at a time, scoped by date range and optional team filter.',
  },
  {
    item: '38 KPI surfaces across 4 sections',
    rationale:
      'Overview (11), Teams (5), Reliability (11), and Billing (11) KPI cards and charts as defined in the KPI Catalog. All surfaces use mock data generated by MSW + Faker.js.',
  },
  {
    item: 'Mock API with MSW + Faker.js',
    rationale:
      'All API responses are generated by MSW handlers using Faker.js seeded generators. The mock produces correlated data that varies correctly by filter combination, making the demo indistinguishable from a real backend.',
  },
  {
    item: 'Visx-based chart components',
    rationale:
      'AreaChart, BarChart, ColumnChart, DonutChart, and dual-axis combination charts built on Visx SVG primitives, wrapped behind the Visualization render-prop abstraction.',
  },
  {
    item: 'Responsive layout (desktop-first)',
    rationale:
      'Two-column KPI grids collapse to single column on small screens (lg:grid-cols-2 breakpoint). Fixed sidebar for /understanding collapses gracefully. Chart containers use percentage widths that adapt to viewport.',
  },
  {
    item: 'WCAG 2.1 AA accessibility',
    rationale:
      'All interactive elements have aria-labels, keyboard navigation, and visible focus indicators. Charts expose data via ARIA table patterns for screen reader users. Color is never the sole indicator of state.',
  },
  {
    item: 'URL-persistent filter state',
    rationale:
      'Date range and team filter are stored in URL search params, surviving page refresh and enabling shareable dashboard links.',
  },
  {
    item: 'Unit and component test coverage',
    rationale:
      'Every new file has a co-located test file. KPI formula functions are unit-tested. UI components are tested with React Testing Library verifying user-visible behavior, not implementation details.',
  },
  {
    item: '/understanding documentation route',
    rationale:
      'A static page documenting all 38 KPIs, 15 key technical decisions, technology choices, scope boundaries, and a glossary. The definitive reference for evaluators and new team members.',
  },
  {
    item: 'Team-level drill-down view',
    rationale:
      'When a specific team is selected in the filter, the Teams section replaces the all-teams table with a focused 4-card summary, use-case distribution, and cost trend for that team.',
  },
]

export const OUT_OF_SCOPE: ScopeEntry[] = [
  {
    item: 'Real-time streaming data',
    rationale:
      'All KPIs show period aggregates (e.g. last 30 days), not live updates. WebSocket or SSE streaming requires a real backend and is a v2 feature.',
  },
  {
    item: 'Individual user drill-down beyond team filter',
    rationale:
      'The dashboard shows org-level and team-level views. Drilling down to individual user behavior (user_id level) is out of scope for v1 due to privacy implications and the additional API surface required.',
  },
  {
    item: 'Alerting and notification system',
    rationale:
      'The dashboard surfaces anomalies visually (cost anomaly calendar, error rate threshold annotation) but does not send email, Slack, or webhook alerts when thresholds are crossed. Alerting is a v2 feature.',
  },
  {
    item: 'Authentication and SSO',
    rationale:
      'The v1 dashboard has no login flow. Auth (OAuth, SAML SSO, API key management) is required for production but is outside the scope of this analytics demonstration.',
  },
  {
    item: 'Backend implementation',
    rationale:
      'There is no real database, no real API server, and no real agent telemetry pipeline. All data is generated by MSW mock handlers. The backend contracts are defined by the TypeScript API types in src/types/api.ts.',
  },
  {
    item: 'Mobile layout',
    rationale:
      'The dashboard is desktop-first (1280px viewport minimum for full layout). Mobile layouts for the fixed sidebar and multi-column KPI grids are deferred to v2.',
  },
  {
    item: 'CSV and PDF export',
    rationale:
      'Data export is a common request but requires either server-side rendering (PDF) or complex client-side serialization (CSV for all 38 KPI datasets). Deferred to v2.',
  },
  {
    item: 'Competitive benchmarking',
    rationale:
      'Comparing an org\'s KPIs against industry benchmarks (e.g. "your error rate is above the P75 for similar orgs") requires aggregated cross-org data that is unavailable in a single-tenant mock.',
  },
  {
    item: 'KPIs requiring accept/discard tracking',
    rationale:
      'Acceptance rate, output acceptance rate, and quality-cost efficiency score require a product feature (explicit accept/discard UI in the agent tool) that does not yet exist. Documented as out of scope to avoid misrepresenting what the dashboard measures.',
  },
  {
    item: 'Multi-org / admin view',
    rationale:
      'The dashboard is scoped to a single org_id. A multi-tenant admin view aggregating across all orgs (for the platform operator) is a separate product surface not included in v1.',
  },
]
